-- SELECT * 
-- FROM "AGENTS" 
-- RIGHT JOIN "ORDERS" 
-- ON "AGENTS"."AGENT_CODE" = "ORDERS"."AGENT_CODE"
-- ORDER BY "AGENTS"."AGENT_CODE";
-- -- LIMIT 10;

SELECT *
FROM "AGENTS"
CROSS JOIN "ORDERS"
ORDER BY "AGENTS"."AGENT_CODE";