SELECT *
FROM "CUSTOMER";

-----------------------------------------------

SELECT "CUSTOMER"."CUST_NAME","ORDERS"."ORD_DESCRIPTION","ORDERS"."ORD_AMOUNT"
FROM "CUSTOMER" 
INNER JOIN "ORDERS" 
ON "CUSTOMER"."CUST_CODE" = "ORDERS"."CUST_CODE"
ORDER BY "CUST_NAME"
LIMIT 10;

-------------------------------------------------
SELECT * 
FROM "CUSTOMER" 
INNER JOIN "ORDERS" 
ON "CUSTOMER"."CUST_CODE" = "ORDERS"."CUST_CODE"
ORDER BY "CUST_NAME"
LIMIT 10;

-------------------------------------------------
SELECT "AGENTS"."AGENT_NAME","AGENTS"."COMMISSION","CUSTOMER"."CUST_NAME","CUSTOMER"."OUTSTANDING_AMT","ORDERS"."ORD_NUM","ORDERS"."ORD_DESCRIPTION"
FROM 
(("AGENTS" INNER JOIN "CUSTOMER" ON "AGENTS"."AGENT_CODE" = "CUSTOMER"."AGENT_CODE")
	       INNER JOIN "ORDERS" ON "CUSTOMER"."AGENT_CODE" = "ORDERS"."AGENT_CODE")
WHERE "OUTSTANDING_AMT" IN (4000,9000,11000)
ORDER BY "OUTSTANDING_AMT";





